### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by paulhibbitts** [absalomedia/grav-plugin-grava11y#2]
I've only recently tried out this Plugin and it is amazingly helpful to diagnose accessibility issues for my Grav projects.

I am working on a big accessibility-friendly update for my Bootstrap 4 Open Matter theme and Open Course Hub skeleton with the help of this plugin. Once I do that, I would like to include your Plugin in the skeleton itself, to help other educators have more accessible content too.

On behalf of the Grav community, thank you for this plugin!

**Comment by absalomedia** [comment]
Hey @paulhibbitts just to let you know we've updated it with the latest edition of Tota11y, so there's going to be more accessibilty goodness in there.

**Comment by paulhibbitts** [comment]
That's awesome news @absalomedia, thanks so much!
