### ISSUE TITLE
Documentation on how to use?

### ISSUE THREAD

**Issue by RCheesley** [absalomedia/grav-plugin-grava11y#3]
Hi folks,

Thanks for this plugin, but I am at a loss to understand how to actually use it, and could not find any kind of documentation on this.

Can you either add something to the readme, or suggest where to find this information?

I'm relatively new to Grav but have a fair bit of experience in other platforms and web development in general.

**Comment by absalomedia** [comment]
Ruth, once the plugin has been activated inside Grav, it will apply itself to whatever theme is being displayed.

There will be a small spectacles icon in the bottom left hand corner of the browser screen when active. Grava11y is essentially a wrapper for the tota11y toolkit from Khan Academy:

Documentation on how the tota11y toolkit works can be found here: https://khan.github.io/tota11y/
